KnowledgeShare/articlefeed/urls.py
from django.urls import path
from .views import ArticleFeedView
from .api.views import ArticleFeedListView


app_name = 'articlefeed'
urlpatterns = [
    path('', ArticleFeedView.as_view(), name='article_feed'),

    # API urls
    path('api/articlefeed', ArticleFeedListView.as_view(), name='article_list'),
]

KnowledgeShare/knowledgebase/urls.py
from django.urls import path
from .views.knowledgebase_views import (KnowledgeBaseView, FolderDeleteView,
                                        FolderEditView, BulkFolderChangeView, BulkDeleteView,
                                        KB_ArticleEditView)
from .views.article_views import (ArticleView, ArticleEditView, ArticleDeleteView,
                                  ArticleImageUploadView, RemoveForeignArticleView)

app_name = 'knowledgebase'
urlpatterns = [
    path('article/<int:article_id>', ArticleView.as_view(), name='article'),
    path('article/create', ArticleEditView.as_view(), name='article_create'),
    path('article/edit/<int:article_id>', ArticleEditView.as_view(), name='article_edit'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/image-upload', ArticleImageUploadView.as_view(), name='article_image_upload'),
    path('article/remove-foreign/<int:article_id>',
         RemoveForeignArticleView.as_view(),
         name='article_remove_foreign'),

    path('folder/edit/<int:pk>', FolderEditView.as_view(), name='folder_edit'),
    path('folder/delete/<int:pk>', FolderDeleteView.as_view(), name='folder_delete'),
    path('folder/bulk-change', BulkFolderChangeView.as_view(), name='bulk_folder_change'),
    path('folder/bulk-delete', BulkDeleteView.as_view(), name='bulk_delete'),

    path('kb/<str:username>', KnowledgeBaseView.as_view(), name='kb'),
    path('kb/<str:username>/<int:folder_id>', KnowledgeBaseView.as_view(), name='kb_id'),
    path('kb/<str:username>/Search', KnowledgeBaseView.as_view(), name='kb_search'),
    path('kb/article/edit/<int:pk>', KB_ArticleEditView.as_view(), name='kb_article_edit'),
]

KnowledgeShare/social/urls.py
from django.urls import path
from rest_framework.schemas import get_schema_view
from KnowledgeShare.utils.api.schema_generators import ServerSchemaGenerator
from .views import DashboardView, MessagesView, NewMessageView, MessageDetailView
from .api.views import (FollowerListView, FollowingListView, FollowUnfollowView,
                        MessagesListView, NotificationsListView)


app_name = 'social'
urlpatterns = [
    path('dashboard/<str:username>', DashboardView.as_view(), name='dashboard'),
    path('messages', MessagesView.as_view(), name='messages'),
    path('messages/create', NewMessageView.as_view(), name='new_message'),
    path('messages/detail/<str:username>', MessageDetailView.as_view(), name='message_detail'),


    # API endpoints
    path('api/following/<int:pk>', FollowingListView.as_view(), name='following'),
    path('api/followers/<int:pk>', FollowerListView.as_view(), name='followers'),
    path('api/follow-unfollow/<int:pk>', FollowUnfollowView.as_view(), name='follow_unfollow'),
    path('api/notifications', NotificationsListView.as_view(), name='notifications'),
    path('api/messages', MessagesListView.as_view(), name='message_api'),
    path('api/openapi', get_schema_view(title='KnowledgeShare.Social',
                                        description='API for the Social app in the project',
                                        generator_class=ServerSchemaGenerator,
                                        version='1.0.0'), name='openapi-schema'),
]

KnowledgeShare/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (RegisterationView, UserSettingsView, DeleteAccountView,
                    LoginRedirectView, LoggingView)
from .forms import LoginForm, ResetPasswodForm, PasswordSetForm

app_name = 'users'
urlpatterns = [
    path('', RegisterationView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(
        template_name='users/login.html',
        authentication_form=LoginForm), name='login'),
    path('logout', auth_views.logout_then_login, name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html',
        form_class=ResetPasswodForm), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        post_reset_login=True,
        success_url=reverse_lazy('users:login_redirect'),
        form_class=PasswordSetForm), name='password_reset_confirm'),
    path('settings', UserSettingsView.as_view(), name='settings'),
    path('delete/account', DeleteAccountView.as_view(), name='delete_account'),
    path('login/redirect', LoginRedirectView.as_view(), name='login_redirect'),
    path('logs', LoggingView.as_view(), name='logs')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('',
         TemplateView.as_view(template_name='landingpage/landingpage.html'),
         name='landing_page'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('management-center/', admin.site.urls),
    path('social/', include('KnowledgeShare.social.urls', namespace='social')),
    path('users/', include('KnowledgeShare.users.urls', namespace='users')),
    path('articlefeed/', include('KnowledgeShare.articlefeed.urls', namespace='articlefeed')),
    path('tinymce/', include('tinymce.urls')),
    path('knowledgebase/',
         include('KnowledgeShare.knowledgebase.urls', namespace='knowledgebase')),
    path('cookie-policy',
         TemplateView.as_view(template_name='policies/cookiepolicy.html'),
         name='cookie_policy'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KnowledgeShare/social/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Message

USER_MODEL = get_user_model()


class NewMessageForm(forms.ModelForm):
    """
    Form to create new message.
    """
    class Meta:
        model = Message
        fields = ['sender', 'recipient', 'content']
        widgets = {
            'sender': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['sender'].initial = self.user.id
        self.fields['recipient'].empty_label = '(Please select)'
        self.fields['recipient'].widget.attrs.update({'class': 'form-select select2'})
        self.fields['recipient'].queryset = self.user.following.all()
        self.fields['content'].widget.attrs.update({'class': 'form-control'})

KnowledgeShare/articlefeed/api/views.py
from django.contrib.auth import get_user_model
from django.db.models import Q
from rest_framework.generics import ListAPIView
from django_filters import rest_framework as filters
from KnowledgeShare.utils.api.pagination import SmallResultSetPagination
from KnowledgeShare.knowledgebase.models import Article
from ..filters import ArticleFeedFilter
from .serializers import ArticleFeedSerializer

USER_MODEL = get_user_model()


class ArticleFeedListView(ListAPIView):
    serializer_class = ArticleFeedSerializer
    pagination_class = SmallResultSetPagination
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = ArticleFeedFilter

    def get_queryset(self):
        queryset = (Article
                    .objects
                    .filter(article_status_id=Article.Article_Status.PUBLISHED)
                    .order_by('-updated_on')
                    )
        if self.request.user.is_authenticated:
            queryset = queryset.filter(~Q(author=self.request.user.id))
        return queryset

KnowledgeShare/articlefeed/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth import get_user_model
from .filters import ArticleFeedFilter

USER_MODEL = get_user_model()


# Create your views here.
class ArticleFeedView(View):
    template_name = 'articlefeed/articlefeed.html'

    def get(self, request, *args, **kwargs):
        filter_form = ArticleFeedFilter(request=request)
        return render(request, self.template_name, {'filter_form': filter_form})

KnowledgeShare/knowledgebase/views/article_views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from ..forms import ArticleForm, ArticleUserForm
from ..models import Article, ArticleImage


class ArticleView(View):
    template_name = 'knowledgebase/article_view.html'
    article_user_form = ArticleForm

    def get(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article_user_form = None
        article = (Article
                   .objects
                   .filter(id=article_id)
                   .select_related('author')
                   .get()
                   )
        if request.user.is_authenticated:
            article_user_form = ArticleUserForm(user=request.user,
                                                initial={'article': article,
                                                         'user': request.user})
        return render(request, self.template_name, {
            'article': article,
            'ArticleUserForm': article_user_form
        })

    def post(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article_user_form = ArticleUserForm(request.POST, user=request.user)
        if article_user_form.is_valid():
            article_user_form.save()
            messages.success(request, 'Article added to knowledgebase!')
        else:
            messages.error(request, article_user_form.errors.as_json(escape_html=True))

        return redirect('knowledgebase:article', article_id=article_id)


class ArticleEditView(LoginRequiredMixin, View):
    template_name = 'knowledgebase/article_edit.html'

    def get(self, request, article_id=None):

        # Creates new article if no id is supplied
        if article_id is None:
            article = Article.objects.create(
                author=request.user,
                article_status_id=Article.Article_Status.DRAFT,
                version_status_id=Article.Version_Status.ACTIVE
            )
            return redirect('knowledgebase:article_edit', article_id=article.id)

        current_article = get_object_or_404(Article, id=article_id, author=request.user)
        article_versions = (Article
                            .objects
                            .filter(uuid=current_article.uuid)
                            .order_by('-id')
                            )
        return render(request, self.template_name, {
            'ArticleForm': ArticleForm(user=request.user, instance=current_article),
            'article_versions': article_versions,
            'article': current_article,
        })

    def post(self, request, article_id):
        """
        Updates an article instance and takes extra
        actions if a submit_type is supllied.

        Submit types:
        1. New_Version: Creates new version of the article.
        2. Publish: Publishes the article.
        """

        article = get_object_or_404(Article, id=article_id, author=request.user)
        form = ArticleForm(request.POST, user=request.user, instance=article)
        submit_type = request.POST['SubmitButton']

        if submit_type:
            submit_type = int(submit_type)

        if submit_type == Article.Version_Status.NEW_VERSION:
            new_version = article.create_new_version()
            messages.info(request, 'New version created')
            return redirect('knowledgebase:article_edit', article_id=new_version.id)

        if form.is_valid():
            form.save()
            if submit_type == Article.Article_Status.PUBLISHED:
                article.publish_article()
                messages.success(request, 'Article published successfully!')
            else:
                messages.success(request, 'Article saved successfully!')
            return redirect('knowledgebase:kb', username=request.user.username)
        else:
            return render(request, self.template_name, {
                'ArticleForm': form,
                'article': article})


class ArticleDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Article
    success_message = 'Article deleted successfully!'

    def form_valid(self, form):
        self.object = self.get_object()
        success_url = self.get_success_url()

        # If deleting active version for article.
        # Deletes all versions as well
        if self.object.version_status_id == Article.Version_Status.ACTIVE:
            Article.objects.filter(uuid=self.object.uuid).delete()
        else:
            self.object.delete()

        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse_lazy('knowledgebase:kb', kwargs={'username': self.request.user.username})


class ArticleImageUploadView(LoginRequiredMixin, View):
    def post(self, request):
        if 'file' in request.FILES:
            article = (Article
                       .objects
                       .get(id=request.POST['article_id'])
                       )
            image = ArticleImage.objects.create(
                article_id=article,
                image=request.FILES['file']
            )
            return JsonResponse({'location': image.image.url})
        else:
            return JsonResponse('No image found', safe=False)


class RemoveForeignArticleView(LoginRequiredMixin, View):
    def post(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article = get_object_or_404(Article, id=article_id)
        article.foreign_users.remove(request.user)
        messages.success(request, 'Article removed from knowledgebase!')

        # Redirects back to the url that mad ethe request
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

KnowledgeShare/social/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View, ListView
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from KnowledgeShare.knowledgebase.models import Article
from .forms import NewMessageForm
from .models import Message

USER_MODEL = get_user_model()


# Create your views here.
class DashboardView(View):
    template_name = 'social/dashboard.html'

    def get(self, request, *args, **kwargs):
        username = kwargs.pop('username', None)
        dasboard_user = get_user_model().objects.get(username=username)
        recent_articles = (Article
                           .objects
                           .filter(author=dasboard_user,
                                   article_status_id=Article.Article_Status.PUBLISHED
                                   )
                           .order_by('-updated_on')[:5]
                           )
        return render(request, self.template_name, {
            'dashboard_user': dasboard_user,
            'recent_articles': recent_articles})


class MessagesView(LoginRequiredMixin, ListView):
    template_name = 'social/messages.html'
    model = Message
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(sender=self.request.user) | Q(recipient=self.request.user))
        queryset = queryset.order_by('conversation_id', '-message_sent_date')
        queryset = queryset.select_related('sender').select_related('recipient')
        queryset = queryset.distinct('conversation_id')
        return queryset


class MessageDetailView(LoginRequiredMixin, View):
    template_name = 'social/message_detail.html'

    def get(self, request, username):
        user = get_object_or_404(USER_MODEL, username=username)
        return render(request, self.template_name, {'chat_user': user})


class NewMessageView(LoginRequiredMixin, View):
    template_name = 'social/new_message.html'

    def get(self, request):
        message_form = NewMessageForm(user=request.user)
        return render(request, self.template_name, {'message_form': message_form})

    def post(self, request):
        message_form = NewMessageForm(request.POST, user=request.user)
        if message_form.is_valid():
            message_form.save()
            messages.success(request, 'Message sent successfully!')
            recipient = message_form.cleaned_data['recipient']
            return redirect('social:message_detail', recipient.username)
        return render(request, self.template_name, {'message_form': message_form})

KnowledgeShare/templates/blocks/confirmation_popup.html
{% comment %}
Reusable confirmation popup. To use this popup in a template put
the 'include' tag at the bottom of the body by your script tags like so.
{% include 'blocks/confirmation_popup.html' with is_deletion=False %}

To use the popup on an element you need to add 'confirmation-popup-class'
to the elements classes and also add the attributes listed below to the element.

attributes:
data-confirm-text - the text to display on the popup
data-confirm-url - the url that the popup is submitting to.
data-confirm-form - optional form for the confirmation to submit
is_deletion - will show 'delete' button instead of 'submit' if True

This popup uses POST when submitting to url.

{% endcomment %}

<!-- Modal -->
  <div class="modal fade" id="confirmation-popup" tabindex="-1" aria-labelledby="confirmation-popupLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-body">
          <div class="text-end">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="text-center pt-2">
            <h5 id="confirmation_popup_title" class="modal-title"></h5>
            <form id="confirmation_popup_form" method="post">
              {% csrf_token %}
              <div class="pt-4">
                  <div class="pe-1 d-inline-block">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                  </div>
                  <div class="ps-1 d-inline-block">
                    {% if is_deletion %}
                    <button type="submit" class="btn btn-danger" id="confirmation_submit_button">Delete</button>
                    {% else %}
                    <button type="submit" class="btn btn-primary" id="confirmation_submit_button">Submit</button>
                    {% endif %}
                  </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  var elements = document.getElementsByClassName("confirmation-popup-class");

  for (var i = 0; i < elements.length; i++) {
    elements[i].addEventListener('click', show_confirmation_popup);
  }

  function show_confirmation_popup(event) {
    var confirmation_popup = new bootstrap.Modal(document.getElementById('confirmation-popup'))
    var button = event.currentTarget;
    var confirm_text = button.getAttribute('data-confirm-text');
    var confirm_url = button.getAttribute('data-confirm-url');

    document.getElementById('confirmation_popup_title').innerHTML = confirm_text
    document.getElementById('confirmation_popup_form').action = confirm_url

    if (button.hasAttribute('data-confirm-form')) {
      document.getElementById('confirmation_submit_button').setAttribute("form", button.getAttribute('data-confirm-form'));
    }

    confirmation_popup.show()
  }

</script>

KnowledgeShare/templates/blocks/desktop_navbar.html
{% url 'social:dashboard' request.user.username as dashboard_url %}
{% url 'knowledgebase:kb' request.user.username as knowledgebase_url %}
{% url 'articlefeed:article_feed' as articlefeed_url %}
{% url 'social:messages' as messages_url %}
{% url 'users:logs' as logs_url %}
{% url 'users:settings' as settings_url %}

<div class="col-nav g-0 nav-bar-desktop">
    <div class="nav-bar-col nav-bg-color text-break">
      <ul class="nav flex-column">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          {% if request.path == dashboard_url %}
            <a class=" icon-active" aria-current="page" href="{{dashboard_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Dashboard"><i class="fa-solid fa-house fa-2x"></i></a>
          {% else %}
            <a class="nav-icon" aria-current="page" href="{{dashboard_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Dashboard"><i class="fa-solid fa-house fa-2x"></i></a>
          {% endif %}
        </li>
        {% endif %}
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          {% if request.path == knowledgebase_url %}
            <a class="icon-active" href="{{knowledgebase_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="KnowledgeBase"><i class="fa-solid fa-folder fa-2x"></i></a>
          {% else %}
            <a class="nav-icon" href="{{knowledgebase_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="KnowledgeBase"><i class="fa-solid fa-folder fa-2x"></i></a>
          {% endif %}
        </li>
        {% endif %}
        <li class="nav-item">
          {% if request.path == articlefeed_url %}
            <a class="icon-active" href="{{articlefeed_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Article feed"><i class="fa-solid fa-newspaper fa-2x"></i></a>
          {% else %}
            <a class="nav-icon" href="{{articlefeed_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Article feed"><i class="fa-solid fa-newspaper fa-2x"></i></a>
          {% endif %}
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          {% if request.path == messages_url %}
          <a class="icon-active" href="{{messages_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Messages"><i class="fa-solid fa-envelope fa-2x"></i></a>
          {% else %}
          <a class="nav-icon" href="{{messages_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Messages"><i class="fa-solid fa-envelope fa-2x"></i></a>
          {% endif %}
        </li>
        {% endif %}
        {% if request.user.is_authenticated and request.user.is_superuser%}
        <li class="nav-item">
          {% if request.path == logs_url %}
            <a class="icon-active" href="{{logs_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Logs"><i class="fa-solid fa-file-code fa-2x"></i></a>
          {% else %}
            <a class="nav-icon" href="{{logs_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Logs"><i class="fa-solid fa-file-code fa-2x"></i></a>
          {% endif %}
        </li>
        {% endif %}
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          {% if request.path == settings_url %}
           <a class="icon-active" href="{{settings_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Settings"><i class="fa-solid fa-gear fa-2x"></i></a>
          {% else %}
           <a class="nav-icon" href="{{settings_url}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Settings"><i class="fa-solid fa-gear fa-2x"></i></a>
          {% endif %}
        </li>
        {% endif %}
      </ul>
    </div>
</div>

KnowledgeShare/templates/blocks/form_popup.html
{% comment %}
Reusable popup with form submission. To use this popup in a template 
use the 'include' tag like so 
{% include 'blocks/form_popup.html' with id='id' title='title' form=Form action="/submit/url"%}

include these attributes in button on your template to activate popup
data-bs-toggle="modal" data-bs-target="#id" where id is what you set as the input for the popup

input vars:
id - the id you will include on the button in your template to activate the popup
title - the header of the popup
form - form you wish for the popup to have
action - the action you want the form to submit too.

{% endcomment %}

<!-- Modal -->
  <div class="modal fade" id="{{id}}"  aria-labelledby="{{id}}Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">{{title}}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form id="{{id}}-form" method="post" action="{{action}}">
                {% csrf_token %}
                {# Include the hidden fields #}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                <div class="pb-4">
                  {{ field.label_tag}}
                  {{ field }}
                  <div style="color: red;">{{ field.errors }}</div>
                </div>
                {% endfor %}
                <div class="text-end">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

KnowledgeShare/templates/blocks/mobile_navbar.html
{% url 'social:dashboard' request.user.username as dashboard_url %}
{% url 'knowledgebase:kb' request.user.username as knowledgebase_url %}
{% url 'articlefeed:article_feed' as articlefeed_url %}
{% url 'social:messages' as messages_url %}
{% url 'users:settings' as settings_url %}

<div class="mobile-nav-bar">
    <nav class="navbar fixed-bottom nav-bg-color text-break">
      <div class="container-fluid">
        <ul class="nav" style="width: 100%">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            {% if request.path == dashboard_url %}
              <a class="icon-active" aria-current="page" href="{{dashboard_url}}" ><i class="fa-solid fa-house fa-xl"></i></a>
            {% else %}
              <a class="nav-icon" aria-current="page" href="{{dashboard_url}}" ><i class="fa-solid fa-house fa-xl"></i></a>
            {% endif %}
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            {% if request.path == knowledgebase_url %}
              <a class="icon-active" href="{{knowledgebase_url}}"><i class="fa-solid fa-folder fa-xl"></i></a>
            {% else %}
              <a class="nav-icon" href="{{knowledgebase_url}}"><i class="fa-solid fa-folder fa-xl"></i></a>
            {% endif %}
          </li>
          {% endif %}
          <li class="nav-item">
            {% if request.path == articlefeed_url %}
              <a class="icon-active" href="{{articlefeed_url}}"><i class="fa-solid fa-newspaper fa-xl"></i></a>
            {% else %}
              <a class="nav-icon" href="{{articlefeed_url}}"><i class="fa-solid fa-newspaper fa-xl"></i></a>
            {% endif %}
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            {% if request.path == messages_url %}
              <a class="icon-active" href="{{messages_url}}"><i class="fa-solid fa-envelope fa-xl"></i></a>
            {% else %}
              <a class="nav-icon" href="{{messages_url}}"><i class="fa-solid fa-envelope fa-xl"></i></a>
            {% endif %}
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            {% if request.path == settings_url %}
             <a class="icon-active" href="{{settings_url}}"><i class="fa-solid fa-gear fa-xl"></i></a>
            {% else %}
             <a class="nav-icon" href="{{settings_url}}"><i class="fa-solid fa-gear fa-xl"></i></a>
            {% endif %}
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>