KnowledgeShare/articlefeed/urls.py
from django.urls import path
from .views import ArticleFeedView
from .api.views import ArticleFeedListView


app_name = 'articlefeed'
urlpatterns = [
    path('', ArticleFeedView.as_view(), name='article_feed'),

    # API urls
    path('api/articlefeed', ArticleFeedListView.as_view(), name='article_list'),
]

KnowledgeShare/knowledgebase/urls.py
from django.urls import path
from .views.knowledgebase_views import (KnowledgeBaseView, FolderDeleteView,
                                        FolderEditView, BulkFolderChangeView, BulkDeleteView,
                                        KB_ArticleEditView)
from .views.article_views import (ArticleView, ArticleEditView, ArticleDeleteView,
                                  ArticleImageUploadView, RemoveForeignArticleView)

app_name = 'knowledgebase'
urlpatterns = [
    path('article/<int:article_id>', ArticleView.as_view(), name='article'),
    path('article/create', ArticleEditView.as_view(), name='article_create'),
    path('article/edit/<int:article_id>', ArticleEditView.as_view(), name='article_edit'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/image-upload', ArticleImageUploadView.as_view(), name='article_image_upload'),
    path('article/remove-foreign/<int:article_id>',
         RemoveForeignArticleView.as_view(),
         name='article_remove_foreign'),

    path('folder/edit/<int:pk>', FolderEditView.as_view(), name='folder_edit'),
    path('folder/delete/<int:pk>', FolderDeleteView.as_view(), name='folder_delete'),
    path('folder/bulk-change', BulkFolderChangeView.as_view(), name='bulk_folder_change'),
    path('folder/bulk-delete', BulkDeleteView.as_view(), name='bulk_delete'),

    path('kb/<str:username>', KnowledgeBaseView.as_view(), name='kb'),
    path('kb/<str:username>/<int:folder_id>', KnowledgeBaseView.as_view(), name='kb_id'),
    path('kb/<str:username>/Search', KnowledgeBaseView.as_view(), name='kb_search'),
    path('kb/article/edit/<int:pk>', KB_ArticleEditView.as_view(), name='kb_article_edit'),
]

KnowledgeShare/social/urls.py
from django.urls import path
from rest_framework.schemas import get_schema_view
from KnowledgeShare.utils.api.schema_generators import ServerSchemaGenerator
from .views import DashboardView, MessagesView, NewMessageView, MessageDetailView
from .api.views import (FollowerListView, FollowingListView, FollowUnfollowView,
                        MessagesListView, NotificationsListView)


app_name = 'social'
urlpatterns = [
    path('dashboard/<str:username>', DashboardView.as_view(), name='dashboard'),
    path('messages', MessagesView.as_view(), name='messages'),
    path('messages/create', NewMessageView.as_view(), name='new_message'),
    path('messages/detail/<str:username>', MessageDetailView.as_view(), name='message_detail'),


    # API endpoints
    path('api/following/<int:pk>', FollowingListView.as_view(), name='following'),
    path('api/followers/<int:pk>', FollowerListView.as_view(), name='followers'),
    path('api/follow-unfollow/<int:pk>', FollowUnfollowView.as_view(), name='follow_unfollow'),
    path('api/notifications', NotificationsListView.as_view(), name='notifications'),
    path('api/messages', MessagesListView.as_view(), name='message_api'),
    path('api/openapi', get_schema_view(title='KnowledgeShare.Social',
                                        description='API for the Social app in the project',
                                        generator_class=ServerSchemaGenerator,
                                        version='1.0.0'), name='openapi-schema'),
]

KnowledgeShare/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (RegisterationView, UserSettingsView, DeleteAccountView,
                    LoginRedirectView, LoggingView)
from .forms import LoginForm, ResetPasswodForm, PasswordSetForm

app_name = 'users'
urlpatterns = [
    path('', RegisterationView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(
        template_name='users/login.html',
        authentication_form=LoginForm), name='login'),
    path('logout', auth_views.logout_then_login, name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html',
        form_class=ResetPasswodForm), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        post_reset_login=True,
        success_url=reverse_lazy('users:login_redirect'),
        form_class=PasswordSetForm), name='password_reset_confirm'),
    path('settings', UserSettingsView.as_view(), name='settings'),
    path('delete/account', DeleteAccountView.as_view(), name='delete_account'),
    path('login/redirect', LoginRedirectView.as_view(), name='login_redirect'),
    path('logs', LoggingView.as_view(), name='logs')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('',
         TemplateView.as_view(template_name='landingpage/landingpage.html'),
         name='landing_page'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('management-center/', admin.site.urls),
    path('social/', include('KnowledgeShare.social.urls', namespace='social')),
    path('users/', include('KnowledgeShare.users.urls', namespace='users')),
    path('articlefeed/', include('KnowledgeShare.articlefeed.urls', namespace='articlefeed')),
    path('tinymce/', include('tinymce.urls')),
    path('knowledgebase/',
         include('KnowledgeShare.knowledgebase.urls', namespace='knowledgebase')),
    path('cookie-policy',
         TemplateView.as_view(template_name='policies/cookiepolicy.html'),
         name='cookie_policy'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KnowledgeShare/knowledgebase/models.py
import uuid as uuid_lib
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.utils.html import strip_tags
from django.utils.text import Truncator
from KnowledgeShare.utils.models import TimeStampedModel


# Create your models here.
class Article(TimeStampedModel):

    class Article_Status(models.IntegerChoices):
        DRAFT = 1, _('Draft')
        PUBLISHED = 2, _('Published')
        ARCHIVED = 3, _('Archived')

    class Version_Status(models.IntegerChoices):
        ACTIVE = 4, _('Active')
        HISTORY = 5, _('History')
        NEW_VERSION = 6, _('New Version')

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200, blank=True)
    slug = models.SlugField(max_length=200, blank=True)
    article_status_id = models.SmallIntegerField(choices=Article_Status.choices)
    content = models.TextField(blank=True)
    version = models.IntegerField(default=0)
    version_status_id = models.SmallIntegerField(choices=Version_Status.choices)
    uuid = models.UUIDField(db_index=True, default=uuid_lib.uuid4, editable=False)
    folder = models.ForeignKey('Folder', on_delete=models.CASCADE, null=True, blank=True)
    foreign_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           through='Article_User',
                                           through_fields=('article', 'user'),
                                           related_name='foreign_articles')

    @property
    def truncated_content(self):
        content = strip_tags(self.content)
        return Truncator(content).words(20)

    def create_new_version(self):
        """
        Creates a new version of an article and returns it.
        """

        (Article
         .objects
         .filter(uuid=self.uuid, version_status_id=Article.Version_Status.NEW_VERSION)
         .delete()
         )
        new_version = (Article
                       .objects
                       .create(author=self.author,
                               title=self.title,
                               slug=self.slug,
                               article_status_id=self.Article_Status.DRAFT,
                               content=self.content,
                               version=self.version + 1,
                               version_status_id=self.Version_Status.NEW_VERSION,
                               uuid=self.uuid,
                               folder=self.folder
                               )
                       )

        return new_version

    def publish_article(self):
        """
        Publishes an article.
        """

        (Article
         .objects
         .filter(Q(uuid=self.uuid), ~Q(id=self.id))
         .update(article_status_id=self.Article_Status.ARCHIVED,
                 version_status_id=self.Version_Status.HISTORY)
         )

        self.article_status_id = Article.Article_Status.PUBLISHED
        self.version_status_id = Article.Version_Status.ACTIVE
        self.save()

        return self


class ArticleImage(models.Model):
    article_id = models.ForeignKey('Article', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='article_images')


class Article_User(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    folder = models.ForeignKey('Folder', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['article', 'user'], name='unique article_user')
        ]


class Folder(TimeStampedModel):
    name = models.CharField(max_length=200)
    parent_folder = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

    @staticmethod
    def UserFolders(user):
        """
        Returns a list of the users folders
        """
        return list(Folder.objects.filter(owner=user))

KnowledgeShare/social/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from KnowledgeShare.utils.models import TimeStampedModel


# Create your models here.
class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.SET_NULL,
                               null=True,
                               related_name='sender')
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  related_name='recipient')
    content = models.TextField()
    message_sent_date = models.DateTimeField(auto_now=True)
    message_read = models.BooleanField(default=False)
    conversation_id = models.CharField(max_length=200)

    def save(self, *args, **kwargs):
        min_id = min(self.sender.id, self.recipient.id)
        max_id = max(self.sender.id, self.recipient.id)
        self.conversation_id = str(min_id) + '-' + str(max_id)

        url = reverse('social:message_detail', args=(self.sender.username,))
        Notification.objects.create(message=f"""
                                    New message from
                                    <a href="{url}"class="text-decoration-none">
                                    @{self.sender.username}</a>
                                    """,
                                    user=self.recipient)
        super(Message, self).save(*args, **kwargs)


class Notification(TimeStampedModel):
    message = models.CharField(max_length=300)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    seen = models.BooleanField(default=False)

KnowledgeShare/social/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Message

USER_MODEL = get_user_model()


class NewMessageForm(forms.ModelForm):
    """
    Form to create new message.
    """
    class Meta:
        model = Message
        fields = ['sender', 'recipient', 'content']
        widgets = {
            'sender': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['sender'].initial = self.user.id
        self.fields['recipient'].empty_label = '(Please select)'
        self.fields['recipient'].widget.attrs.update({'class': 'form-select select2'})
        self.fields['recipient'].queryset = self.user.following.all()
        self.fields['content'].widget.attrs.update({'class': 'form-control'})

KnowledgeShare/articlefeed/api/views.py
from django.contrib.auth import get_user_model
from django.db.models import Q
from rest_framework.generics import ListAPIView
from django_filters import rest_framework as filters
from KnowledgeShare.utils.api.pagination import SmallResultSetPagination
from KnowledgeShare.knowledgebase.models import Article
from ..filters import ArticleFeedFilter
from .serializers import ArticleFeedSerializer

USER_MODEL = get_user_model()


class ArticleFeedListView(ListAPIView):
    serializer_class = ArticleFeedSerializer
    pagination_class = SmallResultSetPagination
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = ArticleFeedFilter

    def get_queryset(self):
        queryset = (Article
                    .objects
                    .filter(article_status_id=Article.Article_Status.PUBLISHED)
                    .order_by('-updated_on')
                    )
        if self.request.user.is_authenticated:
            queryset = queryset.filter(~Q(author=self.request.user.id))
        return queryset

KnowledgeShare/articlefeed/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth import get_user_model
from .filters import ArticleFeedFilter

USER_MODEL = get_user_model()


# Create your views here.
class ArticleFeedView(View):
    template_name = 'articlefeed/articlefeed.html'

    def get(self, request, *args, **kwargs):
        filter_form = ArticleFeedFilter(request=request)
        return render(request, self.template_name, {'filter_form': filter_form})

KnowledgeShare/social/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View, ListView
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from KnowledgeShare.knowledgebase.models import Article
from .forms import NewMessageForm
from .models import Message

USER_MODEL = get_user_model()


# Create your views here.
class DashboardView(View):
    template_name = 'social/dashboard.html'

    def get(self, request, *args, **kwargs):
        username = kwargs.pop('username', None)
        dasboard_user = get_user_model().objects.get(username=username)
        recent_articles = (Article
                           .objects
                           .filter(author=dasboard_user,
                                   article_status_id=Article.Article_Status.PUBLISHED
                                   )
                           .order_by('-updated_on')[:5]
                           )
        return render(request, self.template_name, {
            'dashboard_user': dasboard_user,
            'recent_articles': recent_articles})


class MessagesView(LoginRequiredMixin, ListView):
    template_name = 'social/messages.html'
    model = Message
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(sender=self.request.user) | Q(recipient=self.request.user))
        queryset = queryset.order_by('conversation_id', '-message_sent_date')
        queryset = queryset.select_related('sender').select_related('recipient')
        queryset = queryset.distinct('conversation_id')
        return queryset


class MessageDetailView(LoginRequiredMixin, View):
    template_name = 'social/message_detail.html'

    def get(self, request, username):
        user = get_object_or_404(USER_MODEL, username=username)
        return render(request, self.template_name, {'chat_user': user})


class NewMessageView(LoginRequiredMixin, View):
    template_name = 'social/new_message.html'

    def get(self, request):
        message_form = NewMessageForm(user=request.user)
        return render(request, self.template_name, {'message_form': message_form})

    def post(self, request):
        message_form = NewMessageForm(request.POST, user=request.user)
        if message_form.is_valid():
            message_form.save()
            messages.success(request, 'Message sent successfully!')
            recipient = message_form.cleaned_data['recipient']
            return redirect('social:message_detail', recipient.username)
        return render(request, self.template_name, {'message_form': message_form})

KnowledgeShare/templates/knowledgebase/article_edit.html
{% extends 'layouts/base_knowledgebase.html' %}
{% load static %}

{% block title %}
Edit Article - {{article.title}}
{% endblock title %}

{% block styles %}
<script src="{% static 'knowledgebase/article_edit.js' %}"></script>
{{ArticleForm.media}}
<link rel="stylesheet" href="{% static 'knowledgebase/article_edit.css' %}">
{% endblock styles %}

{% block body %}
<div class="editor-wrapper">
    <div class="pb-3">
        <div class="pb-5 d-inline-block float-end">
                <div class="pe-2 d-inline-block">
                    {% if  article.version_status_id == article.Version_Status.ACTIVE %}
                        <button class="btn btn-danger confirmation-popup-class action-button" 
                                type="submit"
                                data-confirm-text="Deleting active version of article will delete every version. Are you sure?"
                                data-confirm-url="{% url 'knowledgebase:article_delete' article.id %}">Delete Article</button>
                    {% else %}
                        <button class="btn btn-danger confirmation-popup-class action-button" 
                            type="submit"
                            data-confirm-text="Delete article version?"
                            data-confirm-url="{% url 'knowledgebase:article_delete' article.id %}">Delete Version</button>
                    {% endif %}
                </div>
            {% if article.article_status_id == article.Article_Status.DRAFT or article.article_status_id == article.Article_Status.PUBLISHED %}
                <div class="pe-2 d-inline-block">
                    <button class="btn btn-info action-button" type="submit" name="SubmitButton" form="ArticleForm">Save</button>
                </div>
                {% if article.article_status_id == article.Article_Status.DRAFT %}
                    <div class="pe-3 d-inline-block end-div">
                        <button class="btn btn-success action-button" type="submit" name="SubmitButton" value={{article.Article_Status.PUBLISHED}} form="ArticleForm">Publish</button>
                    </div>
                {% else %}
                    <div class="pe-3 d-inline-block end-div">
                        <button class="btn btn-success action-button" type="submit" name="SubmitButton" value={{article.Version_Status.NEW_VERSION}} form="ArticleForm">Create New Version</button>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <div class="d-inline-block">
            <a id="actions-dropdown" class="form-select text-decoration-none article-versions" data-bs-toggle="dropdown">
                Version {{article.version}} - {{article.get_version_status_id_display}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for version in article_versions %}
                <li>
                    <a class="dropdown-item article-versions-item" {% if version.id != article.id %}href="{% url 'knowledgebase:article_edit' version.id %}"{% endif %}>
                        Version {{version.version}} - {{version.get_version_status_id_display}}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <form method="post" id="ArticleForm">
        {% csrf_token %}
        <div class="pb-4 d-inline-block col-12">
            <div class="d-inline-block col-sm-8 article-title">
                <label for="{{ ArticleForm.title.id_for_label }}">Title:</label>
                {{ ArticleForm.title }}
                <div class="form-errors">{{ ArticleForm.title.errors }}</div>
            </div>
            <div class="d-inline-block col-sm-2 folder-dropdown">
                <label for="{{ ArticleForm.folder.id_for_label }}">Folder:</label>
                {{ ArticleForm.folder }}
                <div class="form-errors">{{ ArticleForm.folder.errors }}</div>
            </div>
        </div>
        <div class="pb-3">
            {{ ArticleForm.content }}
            <div class="form-errors">{{ ArticleForm.content.errors }}</div>
        </div>
    </form>
</div>

{% include 'blocks/confirmation_popup.html' %}

{% endblock %}

{% block base_knowledegebase_scripts %}
{% url 'knowledgebase:article_image_upload' as image_uplaod_url %}
{{image_uplaod_url|json_script:"article_upload_url"}}
{{article.id|json_script:"article_id"}}
<script>var token = '{{csrf_token}}';</script>
{% endblock base_knowledegebase_scripts %}

KnowledgeShare/templates/knowledgebase/article_view.html
{% extends 'layouts/base_knowledgebase.html' %}
{% load static %}

{% block title %}
{{article.title}}
{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static 'prism.css' %}">
<link rel="stylesheet" href="{% static 'knowledgebase/article_view.css' %}">
{% endblock styles %}

{% block body %}
<div >
    <a href="{% url 'social:dashboard' article.author.username %}">
    <div class="d-inline-block float-start">
        <img src="{% if article.author.profile_image %}{{article.author.profile_image.url}}{% else %}{% static 'images/user.png' %}{% endif %}" alt="Profile Picture" class="rounded-circle profile-img">
    </div>
    </a>
    <div class="d-inline-block ps-3 pt-1">
        <h5>{% if article.author.first_name %} {{article.author.first_name}} {{article.author.last_name}}{% else %}{{article.author.username}}{% endif %}</h5>
        <small><p>{{article.created_on|date:"N j, Y"}}</p></small>
    </div>
    <div class="d-inline-block float-end">
        {% if article.author == request.user %}
            <a href="{% url 'knowledgebase:article_edit' article.id%}" class="btn btn-primary">Edit</a>
        {% elif  request.user.is_authenticated %}
            {% if request.user in article.foreign_users.all %}
            <form action="{% url 'knowledgebase:article_remove_foreign' article.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-danger">Remove from knowledgebase</button>
            </form>
            {% else %}
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#article-user-form">Add to knowledgebase</button>
            {% endif %}
        {% endif %}
    </div>
</div>
<div class="article pb-5">
    <h1>{{article.title}}</h1>
    <div class="pt-2">
        {% autoescape off %}
            {{article.content}}
        {% endautoescape %}
    </div>
</div>

{% include 'blocks/form_popup.html' with id='article-user-form' title='Add article to knowledgebase' form=ArticleUserForm %}
{% endblock %}

{% block base_knowledegebase_scripts %}
<script src="{% static 'prism.js' %}"></script>
{% endblock base_knowledegebase_scripts %}