KnowledgeShare/articlefeed/urls.py
from django.urls import path
from .views import ArticleFeedView
from .api.views import ArticleFeedListView


app_name = 'articlefeed'
urlpatterns = [
    path('', ArticleFeedView.as_view(), name='article_feed'),

    # API urls
    path('api/articlefeed', ArticleFeedListView.as_view(), name='article_list'),
]

KnowledgeShare/social/urls.py
from django.urls import path
from rest_framework.schemas import get_schema_view
from KnowledgeShare.utils.api.schema_generators import ServerSchemaGenerator
from .views import DashboardView, MessagesView, NewMessageView, MessageDetailView
from .api.views import (FollowerListView, FollowingListView, FollowUnfollowView,
                        MessagesListView, NotificationsListView)


app_name = 'social'
urlpatterns = [
    path('dashboard/<str:username>', DashboardView.as_view(), name='dashboard'),
    path('messages', MessagesView.as_view(), name='messages'),
    path('messages/create', NewMessageView.as_view(), name='new_message'),
    path('messages/detail/<str:username>', MessageDetailView.as_view(), name='message_detail'),


    # API endpoints
    path('api/following/<int:pk>', FollowingListView.as_view(), name='following'),
    path('api/followers/<int:pk>', FollowerListView.as_view(), name='followers'),
    path('api/follow-unfollow/<int:pk>', FollowUnfollowView.as_view(), name='follow_unfollow'),
    path('api/notifications', NotificationsListView.as_view(), name='notifications'),
    path('api/messages', MessagesListView.as_view(), name='message_api'),
    path('api/openapi', get_schema_view(title='KnowledgeShare.Social',
                                        description='API for the Social app in the project',
                                        generator_class=ServerSchemaGenerator,
                                        version='1.0.0'), name='openapi-schema'),
]

KnowledgeShare/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (RegisterationView, UserSettingsView, DeleteAccountView,
                    LoginRedirectView, LoggingView)
from .forms import LoginForm, ResetPasswodForm, PasswordSetForm

app_name = 'users'
urlpatterns = [
    path('', RegisterationView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(
        template_name='users/login.html',
        authentication_form=LoginForm), name='login'),
    path('logout', auth_views.logout_then_login, name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html',
        form_class=ResetPasswodForm), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        post_reset_login=True,
        success_url=reverse_lazy('users:login_redirect'),
        form_class=PasswordSetForm), name='password_reset_confirm'),
    path('settings', UserSettingsView.as_view(), name='settings'),
    path('delete/account', DeleteAccountView.as_view(), name='delete_account'),
    path('login/redirect', LoginRedirectView.as_view(), name='login_redirect'),
    path('logs', LoggingView.as_view(), name='logs')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('',
         TemplateView.as_view(template_name='landingpage/landingpage.html'),
         name='landing_page'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('management-center/', admin.site.urls),
    path('social/', include('KnowledgeShare.social.urls', namespace='social')),
    path('users/', include('KnowledgeShare.users.urls', namespace='users')),
    path('articlefeed/', include('KnowledgeShare.articlefeed.urls', namespace='articlefeed')),
    path('tinymce/', include('tinymce.urls')),
    path('knowledgebase/',
         include('KnowledgeShare.knowledgebase.urls', namespace='knowledgebase')),
    path('cookie-policy',
         TemplateView.as_view(template_name='policies/cookiepolicy.html'),
         name='cookie_policy'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KnowledgeShare/social/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from KnowledgeShare.utils.models import TimeStampedModel


# Create your models here.
class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.SET_NULL,
                               null=True,
                               related_name='sender')
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  related_name='recipient')
    content = models.TextField()
    message_sent_date = models.DateTimeField(auto_now=True)
    message_read = models.BooleanField(default=False)
    conversation_id = models.CharField(max_length=200)

    def save(self, *args, **kwargs):
        min_id = min(self.sender.id, self.recipient.id)
        max_id = max(self.sender.id, self.recipient.id)
        self.conversation_id = str(min_id) + '-' + str(max_id)

        url = reverse('social:message_detail', args=(self.sender.username,))
        Notification.objects.create(message=f"""
                                    New message from
                                    <a href="{url}"class="text-decoration-none">
                                    @{self.sender.username}</a>
                                    """,
                                    user=self.recipient)
        super(Message, self).save(*args, **kwargs)


class Notification(TimeStampedModel):
    message = models.CharField(max_length=300)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    seen = models.BooleanField(default=False)

KnowledgeShare/social/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Message

USER_MODEL = get_user_model()


class NewMessageForm(forms.ModelForm):
    """
    Form to create new message.
    """
    class Meta:
        model = Message
        fields = ['sender', 'recipient', 'content']
        widgets = {
            'sender': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['sender'].initial = self.user.id
        self.fields['recipient'].empty_label = '(Please select)'
        self.fields['recipient'].widget.attrs.update({'class': 'form-select select2'})
        self.fields['recipient'].queryset = self.user.following.all()
        self.fields['content'].widget.attrs.update({'class': 'form-control'})

KnowledgeShare/articlefeed/api/views.py
from django.contrib.auth import get_user_model
from django.db.models import Q
from rest_framework.generics import ListAPIView
from django_filters import rest_framework as filters
from KnowledgeShare.utils.api.pagination import SmallResultSetPagination
from KnowledgeShare.knowledgebase.models import Article
from ..filters import ArticleFeedFilter
from .serializers import ArticleFeedSerializer

USER_MODEL = get_user_model()


class ArticleFeedListView(ListAPIView):
    serializer_class = ArticleFeedSerializer
    pagination_class = SmallResultSetPagination
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = ArticleFeedFilter

    def get_queryset(self):
        queryset = (Article
                    .objects
                    .filter(article_status_id=Article.Article_Status.PUBLISHED)
                    .order_by('-updated_on')
                    )
        if self.request.user.is_authenticated:
            queryset = queryset.filter(~Q(author=self.request.user.id))
        return queryset

KnowledgeShare/articlefeed/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth import get_user_model
from .filters import ArticleFeedFilter

USER_MODEL = get_user_model()


# Create your views here.
class ArticleFeedView(View):
    template_name = 'articlefeed/articlefeed.html'

    def get(self, request, *args, **kwargs):
        filter_form = ArticleFeedFilter(request=request)
        return render(request, self.template_name, {'filter_form': filter_form})

KnowledgeShare/knowledgebase/views/article_views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from ..forms import ArticleForm, ArticleUserForm
from ..models import Article, ArticleImage


class ArticleView(View):
    template_name = 'knowledgebase/article_view.html'
    article_user_form = ArticleForm

    def get(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article_user_form = None
        article = (Article
                   .objects
                   .filter(id=article_id)
                   .select_related('author')
                   .get()
                   )
        if request.user.is_authenticated:
            article_user_form = ArticleUserForm(user=request.user,
                                                initial={'article': article,
                                                         'user': request.user})
        return render(request, self.template_name, {
            'article': article,
            'ArticleUserForm': article_user_form
        })

    def post(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article_user_form = ArticleUserForm(request.POST, user=request.user)
        if article_user_form.is_valid():
            article_user_form.save()
            messages.success(request, 'Article added to knowledgebase!')
        else:
            messages.error(request, article_user_form.errors.as_json(escape_html=True))

        return redirect('knowledgebase:article', article_id=article_id)


class ArticleEditView(LoginRequiredMixin, View):
    template_name = 'knowledgebase/article_edit.html'

    def get(self, request, article_id=None):

        # Creates new article if no id is supplied
        if article_id is None:
            article = Article.objects.create(
                author=request.user,
                article_status_id=Article.Article_Status.DRAFT,
                version_status_id=Article.Version_Status.ACTIVE
            )
            return redirect('knowledgebase:article_edit', article_id=article.id)

        current_article = get_object_or_404(Article, id=article_id, author=request.user)
        article_versions = (Article
                            .objects
                            .filter(uuid=current_article.uuid)
                            .order_by('-id')
                            )
        return render(request, self.template_name, {
            'ArticleForm': ArticleForm(user=request.user, instance=current_article),
            'article_versions': article_versions,
            'article': current_article,
        })

    def post(self, request, article_id):
        """
        Updates an article instance and takes extra
        actions if a submit_type is supllied.

        Submit types:
        1. New_Version: Creates new version of the article.
        2. Publish: Publishes the article.
        """

        article = get_object_or_404(Article, id=article_id, author=request.user)
        form = ArticleForm(request.POST, user=request.user, instance=article)
        submit_type = request.POST['SubmitButton']

        if submit_type:
            submit_type = int(submit_type)

        if submit_type == Article.Version_Status.NEW_VERSION:
            new_version = article.create_new_version()
            messages.info(request, 'New version created')
            return redirect('knowledgebase:article_edit', article_id=new_version.id)

        if form.is_valid():
            form.save()
            if submit_type == Article.Article_Status.PUBLISHED:
                article.publish_article()
                messages.success(request, 'Article published successfully!')
            else:
                messages.success(request, 'Article saved successfully!')
            return redirect('knowledgebase:kb', username=request.user.username)
        else:
            return render(request, self.template_name, {
                'ArticleForm': form,
                'article': article})


class ArticleDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Article
    success_message = 'Article deleted successfully!'

    def form_valid(self, form):
        self.object = self.get_object()
        success_url = self.get_success_url()

        # If deleting active version for article.
        # Deletes all versions as well
        if self.object.version_status_id == Article.Version_Status.ACTIVE:
            Article.objects.filter(uuid=self.object.uuid).delete()
        else:
            self.object.delete()

        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse_lazy('knowledgebase:kb', kwargs={'username': self.request.user.username})


class ArticleImageUploadView(LoginRequiredMixin, View):
    def post(self, request):
        if 'file' in request.FILES:
            article = (Article
                       .objects
                       .get(id=request.POST['article_id'])
                       )
            image = ArticleImage.objects.create(
                article_id=article,
                image=request.FILES['file']
            )
            return JsonResponse({'location': image.image.url})
        else:
            return JsonResponse('No image found', safe=False)


class RemoveForeignArticleView(LoginRequiredMixin, View):
    def post(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article = get_object_or_404(Article, id=article_id)
        article.foreign_users.remove(request.user)
        messages.success(request, 'Article removed from knowledgebase!')

        # Redirects back to the url that mad ethe request
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

KnowledgeShare/social/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View, ListView
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from KnowledgeShare.knowledgebase.models import Article
from .forms import NewMessageForm
from .models import Message

USER_MODEL = get_user_model()


# Create your views here.
class DashboardView(View):
    template_name = 'social/dashboard.html'

    def get(self, request, *args, **kwargs):
        username = kwargs.pop('username', None)
        dasboard_user = get_user_model().objects.get(username=username)
        recent_articles = (Article
                           .objects
                           .filter(author=dasboard_user,
                                   article_status_id=Article.Article_Status.PUBLISHED
                                   )
                           .order_by('-updated_on')[:5]
                           )
        return render(request, self.template_name, {
            'dashboard_user': dasboard_user,
            'recent_articles': recent_articles})


class MessagesView(LoginRequiredMixin, ListView):
    template_name = 'social/messages.html'
    model = Message
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(sender=self.request.user) | Q(recipient=self.request.user))
        queryset = queryset.order_by('conversation_id', '-message_sent_date')
        queryset = queryset.select_related('sender').select_related('recipient')
        queryset = queryset.distinct('conversation_id')
        return queryset


class MessageDetailView(LoginRequiredMixin, View):
    template_name = 'social/message_detail.html'

    def get(self, request, username):
        user = get_object_or_404(USER_MODEL, username=username)
        return render(request, self.template_name, {'chat_user': user})


class NewMessageView(LoginRequiredMixin, View):
    template_name = 'social/new_message.html'

    def get(self, request):
        message_form = NewMessageForm(user=request.user)
        return render(request, self.template_name, {'message_form': message_form})

    def post(self, request):
        message_form = NewMessageForm(request.POST, user=request.user)
        if message_form.is_valid():
            message_form.save()
            messages.success(request, 'Message sent successfully!')
            recipient = message_form.cleaned_data['recipient']
            return redirect('social:message_detail', recipient.username)
        return render(request, self.template_name, {'message_form': message_form})

KnowledgeShare/templates/users/login.html
{% extends 'layouts/base_users.html' %}
{% load static %}

{% block title %}
Login
{% endblock title %}

{% block meta %}
<meta name="description" content="Log into your KnowledgeShare account.">
<meta property="og:description" content="Login to KnowledgeShare.">
{% endblock meta %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href='{% static 'users/login.css' %}'>
{% endblock styles %}


{% block main %}
{{ block.super }}

<div class="container pt-5 ">
    <div class="row" style="height: 100vh;">
        <div class="col-lg-7">
            <div class="welcome-heading animate__animated animate__fadeIn animate__slow">
                <h1 class="text-white" >Welcome!</h1>
                <h4 class="text-white">Sign in or register for an account today <br> to start building your knowledgebase.</h4>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="vertical-center">
                <div class="card shadow-lg" >
                    <div class="card-body">
                        {% if form.errors %}
                        <div class="form-errors">
                        <ul>
                            <li>Invalid username/password</li>
                        </ul>
                        </div>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="pb-3">
                                {{ field.label_tag}}
                                {{ field }}
                                <div class="form-errors">{{ field.errors }}</div>
                                </div>
                            {% endfor %}
                            <div class="d-inline-block">
                                <button type="submit" class="btn btn-primary">Log in</button>
                                <small class="ps-2">
                                    <a href="{% url 'users:password_reset' %}" style="text-decoration: none;">Forgot password?</a>
                                </small>
                            </div>
                        </form>
                        <div style="text-align: center;"><small>Don't have an account? <a href="{% url 'users:register' %}" style="text-decoration: none;">Sign up</a></small></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12" style="text-align: center;">
            <div class="fixed-bottom">
                <small><a href='https://www.freepik.com/vectors/background' style="color: white; opacity: 30%;">Background vector created by freepik - www.freepik.com</a></small>
            </div>
        </div>
    </div>  
</div>
{% endblock main %}

KnowledgeShare/templates/users/logs.html
{% extends 'layouts/base_knowledgebase.html' %}
{% load static %}
{% load utils_tags %}

{% block title %}
Logs
{% endblock title %}

{% block styles %}
<link rel="stylesheet" href='{% static 'users/logs.css' %}'>
{% endblock styles %}

{% block body %}

<div class="card mb-5">
  <div class="card-body d">
    <form method="get" action="{% url 'users:logs' %}">
      <div class="col-2 d-inline-block me-3">
        <label for="DateInput" class="form-label">Date:</label>
        <input type="date" class="form-control" id="DateInput" name="date">
      </div>
      <div class="col-3 d-inline-block">
        <button type="submit" class="btn btn-primary align-baseline">Search</button>
      </div>
    </form>
  </div>
</div>

<table class="table table-bordered table-light table-striped">
  <thead>
    <tr>
      <th scope="col">Level</th>
      <th scope="col">Time of Log</th>
      <th scope="col">Module</th>
      <th scope="col">Message</th>
    </tr>
  </thead>
  <tbody>
    {% for log in logs %}
      <tr>
        <td>{{log.log.level}}</td>
        <td>{{log.log.time|date_time:"%Y-%m-%d %H:%M:%S,%f~%m/%d/%Y %H:%M:%S"}}</td>
        <td>{{log.log.module}}</td>
        <td>{{log.log.message}}</td>
        <td>
          {% if log.log.traceback %}
            <a data-bs-toggle="collapse" href="#collapse{{ forloop.counter }}" role="button" aria-expanded="false" aria-controls="collapse">
              Expand
            </a>
          {% endif %}
        </td>
      </tr>
      {% if log.log.traceback %}
        <tr class="collapse" id="collapse{{ forloop.counter }}">
          <td colspan="5">{{log.log.traceback|linebreaksbr}}</td>
        </tr>
      {% endif %}    
    {% endfor %}
  </tbody>
</table>
{% endblock body %}

KnowledgeShare/templates/users/password_reset.html
{% extends 'layouts/base_users.html' %}
{% load static %}

{% block title %}
Password Reset
{% endblock title %}

{% block meta %}
<meta name="description" content="Reset the password for the users account.">
{% endblock meta %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href='{% static 'users/card_placement.css' %}'>
{% endblock styles %}

{% block main %}
{{ block.super }}
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="password-reset-card-placement">
            <div class="card shadow-lg" >
                <div class="card-body">
                    <h5 class="card-title">Reset Password</h5>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="pb-3">
                                {{ field.label_tag}}
                                {{ field }}
                                <div class="form-errors">{{ field.errors }}</div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Request Password Reset</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12" style="text-align: center;">
        <div class="fixed-bottom">
            <small><a href='https://www.freepik.com/vectors/background' style="color: white; opacity: 30%;">Background vector created by freepik - www.freepik.com</a></small>
        </div>
    </div>
</div>
{% endblock main %}

KnowledgeShare/templates/users/password_reset_confirm.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
Password Reset - Set New Password
{% endblock title %}

{% block meta %}
<meta name="description" content="Set the new password for the account">
{% endblock meta %}

{% block styles %}
<link rel="stylesheet" href='{% static 'users/card_placement.css' %}'>
{% endblock styles %}

{% block main %}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="password-confirm-card-placement">
            <div class="card shadow-lg" >
                <div class="card-body">
                    <h5 class="card-title">Reset Password</h5>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="pb-3">
                                {{ field.label_tag}}
                                {{ field }}
                                <div class="form-errors">{{ field.errors }}</div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Reset Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12" style="text-align: center;">
        <div class="fixed-bottom">
            <small><a href='https://www.freepik.com/vectors/background' style="color: white; opacity: 30%;">Background vector created by freepik - www.freepik.com</a></small>
        </div>
    </div>
</div>
{% endblock main %}

KnowledgeShare/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

KnowledgeShare/templates/users/register.html
{% extends 'layouts/base_users.html' %}
{% load static %}

{% block title %}
Register
{% endblock title %}

{% block meta %}
<meta name="description" content="Sign up for KnowledgeShare today for free and start building your Knowledgebase.">
<meta property="og:description" content="Sign up for KnowledgeShare today!">
{% endblock meta %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href='{% static 'users/card_placement.css' %}'>
{% endblock styles %}

{% block main %}
{{ block.super }}
<div class="container pt-5">
    <div class="register-container pb-5">
    <div class="d-flex justify-content-center pb-5 position-relative">
        <div class="card-placement">
            <div class="card shadow-lg position-relative" style="z-index: 9;">
                <div class="card-body">
                    <h5 class="card-title">Sign Up</h5>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in RegisterForm %}
                            <div class="pb-3">
                                {{ field.label_tag}}
                                {{ field }}
                                <div class="form-errors">{{ field.errors }}</div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary position-relative">Sign Up</button>
                    </form>
                    <div style="padding-top: 5px;"><small>Already have an account? <a href="{% url 'users:login' %}" style="text-decoration: none;">Log in here</a></small></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 z-0" style="text-align: center;">
        <div class="fixed-bottom" style="z-index: 1;">
            <small><a href='https://www.freepik.com/vectors/background' style="color: white; opacity: 30%; z-index: 1; position: relative;">Background vector created by freepik - www.freepik.com</a></small>
        </div>
    </div>
    </div>
</div>
{% endblock main %}

KnowledgeShare/templates/users/settings.html
{% extends 'layouts/base_knowledgebase.html' %}
{% load static %}

{% block title %}
Settings
{% endblock title %}

{% block meta %}
<meta name="description" content="The users settings page to change their account information.">
{% endblock meta %}

{% block styles %}
<link rel="stylesheet" href='{% static 'users/settings.css' %}'>
{% endblock styles %}

{% block body %}
<div class="settings-div w-100 pb-5">
    <div class="text-nowrap">
        <ul class="nav settings-nav" id="SettingsNav" role="tablist">
            <li>
              <a class="nav-link settings-nav-item active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" role="tab" aria-controls="home" aria-selected="true">Account</a>
            </li>
        </ul>
    </div>
    <div class="settings-nav-border"></div>
    <div class="tab-content settings-tab-content w-100" id="SettingsTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
          <div class="border-bottom w-75">
            <h1>Account Settings</h1>
          </div>
          <div class="pt-3 pb-5 account-settings-form">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in UserForm %}
              <div class="pb-4">
                {{ field.label_tag }}
                <br>
                {{ field }}
                <div class="form-errors">{{ field.errors }}</div>
              </div>
              {% endfor %}
              <button type="submit" name="user-settings-form" class="btn btn-primary">Save</button>
            </form>
          </div>
          <div class="pt-4 pb-5 account-settings-form">
            <h5>Change Password:</h5>
            <form method="post">
              {% csrf_token %}
              {% for field in PasswordChangeForm %}
              <div class="pb-4">
                {{ field.label_tag }}
                <br>
                {{ field }}
                <div class="form-errors">{{ field.errors }}</div>
              </div>
              {% endfor %}
              <button type="submit" name="change-password-form" class="btn btn-primary">Submit</button>
            </form>
          </div>
          <h5 class="lh-1" style="color: rgb(216, 0, 0);">Danger</h5>
          <div class="delete-account-div">
            <button type="button" 
                    class="btn btn-danger confirmation-popup-class"
                    data-confirm-url="{% url 'users:delete_account' %}"
                    data-confirm-text="Deleting account is irreversible. Are you sure?">Delete Account</button>
          </div>
        </div>
      </div>
    </div>
</div>

{% include 'blocks/confirmation_popup.html' with is_deletion=True %}
{% endblock body %}