KnowledgeShare/articlefeed/urls.py
from django.urls import path
from .views import ArticleFeedView
from .api.views import ArticleFeedListView


app_name = 'articlefeed'
urlpatterns = [
    path('', ArticleFeedView.as_view(), name='article_feed'),

    # API urls
    path('api/articlefeed', ArticleFeedListView.as_view(), name='article_list'),
]

KnowledgeShare/knowledgebase/urls.py
from django.urls import path
from .views.knowledgebase_views import (KnowledgeBaseView, FolderDeleteView,
                                        FolderEditView, BulkFolderChangeView, BulkDeleteView,
                                        KB_ArticleEditView)
from .views.article_views import (ArticleView, ArticleEditView, ArticleDeleteView,
                                  ArticleImageUploadView, RemoveForeignArticleView)

app_name = 'knowledgebase'
urlpatterns = [
    path('article/<int:article_id>', ArticleView.as_view(), name='article'),
    path('article/create', ArticleEditView.as_view(), name='article_create'),
    path('article/edit/<int:article_id>', ArticleEditView.as_view(), name='article_edit'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/image-upload', ArticleImageUploadView.as_view(), name='article_image_upload'),
    path('article/remove-foreign/<int:article_id>',
         RemoveForeignArticleView.as_view(),
         name='article_remove_foreign'),

    path('folder/edit/<int:pk>', FolderEditView.as_view(), name='folder_edit'),
    path('folder/delete/<int:pk>', FolderDeleteView.as_view(), name='folder_delete'),
    path('folder/bulk-change', BulkFolderChangeView.as_view(), name='bulk_folder_change'),
    path('folder/bulk-delete', BulkDeleteView.as_view(), name='bulk_delete'),

    path('kb/<str:username>', KnowledgeBaseView.as_view(), name='kb'),
    path('kb/<str:username>/<int:folder_id>', KnowledgeBaseView.as_view(), name='kb_id'),
    path('kb/<str:username>/Search', KnowledgeBaseView.as_view(), name='kb_search'),
    path('kb/article/edit/<int:pk>', KB_ArticleEditView.as_view(), name='kb_article_edit'),
]

KnowledgeShare/social/urls.py
from django.urls import path
from rest_framework.schemas import get_schema_view
from KnowledgeShare.utils.api.schema_generators import ServerSchemaGenerator
from .views import DashboardView, MessagesView, NewMessageView, MessageDetailView
from .api.views import (FollowerListView, FollowingListView, FollowUnfollowView,
                        MessagesListView, NotificationsListView)


app_name = 'social'
urlpatterns = [
    path('dashboard/<str:username>', DashboardView.as_view(), name='dashboard'),
    path('messages', MessagesView.as_view(), name='messages'),
    path('messages/create', NewMessageView.as_view(), name='new_message'),
    path('messages/detail/<str:username>', MessageDetailView.as_view(), name='message_detail'),


    # API endpoints
    path('api/following/<int:pk>', FollowingListView.as_view(), name='following'),
    path('api/followers/<int:pk>', FollowerListView.as_view(), name='followers'),
    path('api/follow-unfollow/<int:pk>', FollowUnfollowView.as_view(), name='follow_unfollow'),
    path('api/notifications', NotificationsListView.as_view(), name='notifications'),
    path('api/messages', MessagesListView.as_view(), name='message_api'),
    path('api/openapi', get_schema_view(title='KnowledgeShare.Social',
                                        description='API for the Social app in the project',
                                        generator_class=ServerSchemaGenerator,
                                        version='1.0.0'), name='openapi-schema'),
]

KnowledgeShare/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (RegisterationView, UserSettingsView, DeleteAccountView,
                    LoginRedirectView, LoggingView)
from .forms import LoginForm, ResetPasswodForm, PasswordSetForm

app_name = 'users'
urlpatterns = [
    path('', RegisterationView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(
        template_name='users/login.html',
        authentication_form=LoginForm), name='login'),
    path('logout', auth_views.logout_then_login, name='logout'),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html',
        form_class=ResetPasswodForm), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        post_reset_login=True,
        success_url=reverse_lazy('users:login_redirect'),
        form_class=PasswordSetForm), name='password_reset_confirm'),
    path('settings', UserSettingsView.as_view(), name='settings'),
    path('delete/account', DeleteAccountView.as_view(), name='delete_account'),
    path('login/redirect', LoginRedirectView.as_view(), name='login_redirect'),
    path('logs', LoggingView.as_view(), name='logs')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('',
         TemplateView.as_view(template_name='landingpage/landingpage.html'),
         name='landing_page'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('management-center/', admin.site.urls),
    path('social/', include('KnowledgeShare.social.urls', namespace='social')),
    path('users/', include('KnowledgeShare.users.urls', namespace='users')),
    path('articlefeed/', include('KnowledgeShare.articlefeed.urls', namespace='articlefeed')),
    path('tinymce/', include('tinymce.urls')),
    path('knowledgebase/',
         include('KnowledgeShare.knowledgebase.urls', namespace='knowledgebase')),
    path('cookie-policy',
         TemplateView.as_view(template_name='policies/cookiepolicy.html'),
         name='cookie_policy'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KnowledgeShare/social/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Message

USER_MODEL = get_user_model()


class NewMessageForm(forms.ModelForm):
    """
    Form to create new message.
    """
    class Meta:
        model = Message
        fields = ['sender', 'recipient', 'content']
        widgets = {
            'sender': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['sender'].initial = self.user.id
        self.fields['recipient'].empty_label = '(Please select)'
        self.fields['recipient'].widget.attrs.update({'class': 'form-select select2'})
        self.fields['recipient'].queryset = self.user.following.all()
        self.fields['content'].widget.attrs.update({'class': 'form-control'})

KnowledgeShare/articlefeed/api/views.py
from django.contrib.auth import get_user_model
from django.db.models import Q
from rest_framework.generics import ListAPIView
from django_filters import rest_framework as filters
from KnowledgeShare.utils.api.pagination import SmallResultSetPagination
from KnowledgeShare.knowledgebase.models import Article
from ..filters import ArticleFeedFilter
from .serializers import ArticleFeedSerializer

USER_MODEL = get_user_model()


class ArticleFeedListView(ListAPIView):
    serializer_class = ArticleFeedSerializer
    pagination_class = SmallResultSetPagination
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = ArticleFeedFilter

    def get_queryset(self):
        queryset = (Article
                    .objects
                    .filter(article_status_id=Article.Article_Status.PUBLISHED)
                    .order_by('-updated_on')
                    )
        if self.request.user.is_authenticated:
            queryset = queryset.filter(~Q(author=self.request.user.id))
        return queryset

KnowledgeShare/articlefeed/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth import get_user_model
from .filters import ArticleFeedFilter

USER_MODEL = get_user_model()


# Create your views here.
class ArticleFeedView(View):
    template_name = 'articlefeed/articlefeed.html'

    def get(self, request, *args, **kwargs):
        filter_form = ArticleFeedFilter(request=request)
        return render(request, self.template_name, {'filter_form': filter_form})

KnowledgeShare/knowledgebase/views/article_views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from ..forms import ArticleForm, ArticleUserForm
from ..models import Article, ArticleImage


class ArticleView(View):
    template_name = 'knowledgebase/article_view.html'
    article_user_form = ArticleForm

    def get(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article_user_form = None
        article = (Article
                   .objects
                   .filter(id=article_id)
                   .select_related('author')
                   .get()
                   )
        if request.user.is_authenticated:
            article_user_form = ArticleUserForm(user=request.user,
                                                initial={'article': article,
                                                         'user': request.user})
        return render(request, self.template_name, {
            'article': article,
            'ArticleUserForm': article_user_form
        })

    def post(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article_user_form = ArticleUserForm(request.POST, user=request.user)
        if article_user_form.is_valid():
            article_user_form.save()
            messages.success(request, 'Article added to knowledgebase!')
        else:
            messages.error(request, article_user_form.errors.as_json(escape_html=True))

        return redirect('knowledgebase:article', article_id=article_id)


class ArticleEditView(LoginRequiredMixin, View):
    template_name = 'knowledgebase/article_edit.html'

    def get(self, request, article_id=None):

        # Creates new article if no id is supplied
        if article_id is None:
            article = Article.objects.create(
                author=request.user,
                article_status_id=Article.Article_Status.DRAFT,
                version_status_id=Article.Version_Status.ACTIVE
            )
            return redirect('knowledgebase:article_edit', article_id=article.id)

        current_article = get_object_or_404(Article, id=article_id, author=request.user)
        article_versions = (Article
                            .objects
                            .filter(uuid=current_article.uuid)
                            .order_by('-id')
                            )
        return render(request, self.template_name, {
            'ArticleForm': ArticleForm(user=request.user, instance=current_article),
            'article_versions': article_versions,
            'article': current_article,
        })

    def post(self, request, article_id):
        """
        Updates an article instance and takes extra
        actions if a submit_type is supllied.

        Submit types:
        1. New_Version: Creates new version of the article.
        2. Publish: Publishes the article.
        """

        article = get_object_or_404(Article, id=article_id, author=request.user)
        form = ArticleForm(request.POST, user=request.user, instance=article)
        submit_type = request.POST['SubmitButton']

        if submit_type:
            submit_type = int(submit_type)

        if submit_type == Article.Version_Status.NEW_VERSION:
            new_version = article.create_new_version()
            messages.info(request, 'New version created')
            return redirect('knowledgebase:article_edit', article_id=new_version.id)

        if form.is_valid():
            form.save()
            if submit_type == Article.Article_Status.PUBLISHED:
                article.publish_article()
                messages.success(request, 'Article published successfully!')
            else:
                messages.success(request, 'Article saved successfully!')
            return redirect('knowledgebase:kb', username=request.user.username)
        else:
            return render(request, self.template_name, {
                'ArticleForm': form,
                'article': article})


class ArticleDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Article
    success_message = 'Article deleted successfully!'

    def form_valid(self, form):
        self.object = self.get_object()
        success_url = self.get_success_url()

        # If deleting active version for article.
        # Deletes all versions as well
        if self.object.version_status_id == Article.Version_Status.ACTIVE:
            Article.objects.filter(uuid=self.object.uuid).delete()
        else:
            self.object.delete()

        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse_lazy('knowledgebase:kb', kwargs={'username': self.request.user.username})


class ArticleImageUploadView(LoginRequiredMixin, View):
    def post(self, request):
        if 'file' in request.FILES:
            article = (Article
                       .objects
                       .get(id=request.POST['article_id'])
                       )
            image = ArticleImage.objects.create(
                article_id=article,
                image=request.FILES['file']
            )
            return JsonResponse({'location': image.image.url})
        else:
            return JsonResponse('No image found', safe=False)


class RemoveForeignArticleView(LoginRequiredMixin, View):
    def post(self, request, **kwargs):
        article_id = kwargs.pop('article_id', None)
        article = get_object_or_404(Article, id=article_id)
        article.foreign_users.remove(request.user)
        messages.success(request, 'Article removed from knowledgebase!')

        # Redirects back to the url that mad ethe request
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

KnowledgeShare/social/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View, ListView
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from KnowledgeShare.knowledgebase.models import Article
from .forms import NewMessageForm
from .models import Message

USER_MODEL = get_user_model()


# Create your views here.
class DashboardView(View):
    template_name = 'social/dashboard.html'

    def get(self, request, *args, **kwargs):
        username = kwargs.pop('username', None)
        dasboard_user = get_user_model().objects.get(username=username)
        recent_articles = (Article
                           .objects
                           .filter(author=dasboard_user,
                                   article_status_id=Article.Article_Status.PUBLISHED
                                   )
                           .order_by('-updated_on')[:5]
                           )
        return render(request, self.template_name, {
            'dashboard_user': dasboard_user,
            'recent_articles': recent_articles})


class MessagesView(LoginRequiredMixin, ListView):
    template_name = 'social/messages.html'
    model = Message
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(sender=self.request.user) | Q(recipient=self.request.user))
        queryset = queryset.order_by('conversation_id', '-message_sent_date')
        queryset = queryset.select_related('sender').select_related('recipient')
        queryset = queryset.distinct('conversation_id')
        return queryset


class MessageDetailView(LoginRequiredMixin, View):
    template_name = 'social/message_detail.html'

    def get(self, request, username):
        user = get_object_or_404(USER_MODEL, username=username)
        return render(request, self.template_name, {'chat_user': user})


class NewMessageView(LoginRequiredMixin, View):
    template_name = 'social/new_message.html'

    def get(self, request):
        message_form = NewMessageForm(user=request.user)
        return render(request, self.template_name, {'message_form': message_form})

    def post(self, request):
        message_form = NewMessageForm(request.POST, user=request.user)
        if message_form.is_valid():
            message_form.save()
            messages.success(request, 'Message sent successfully!')
            recipient = message_form.cleaned_data['recipient']
            return redirect('social:message_detail', recipient.username)
        return render(request, self.template_name, {'message_form': message_form})

KnowledgeShare/templates/social/dashboard.html
{% extends 'layouts/base_knowledgebase.html' %}
{% load static %}

{% block title %}
Dashboard
{% endblock title %}

{% block meta %}
<meta name="description" content="Dashboard of a user's account/profile,">
<meta property="og:description" content="View {{dashboard_user.username}}'s profile!">
{% endblock meta %}

{% block styles %}
<link rel="stylesheet" href='{% static 'social/dashboard.css' %}'>
{% endblock styles %}

{% block body %}
<div class="pb-5">
<div class="card text-center w-100">
    <div class="card-body">
      <div class="card-title">
        <div>
            <img src="{% if dashboard_user.profile_image %}{{dashboard_user.profile_image.url}}{% else %}{% static 'images/user.png' %}{% endif %}" alt="Profile Picture" class="rounded-circle profile-img">
        </div>
        {% if  dashboard_user.first_name and dashboard_user.last_name %}
            <h4>
                {{dashboard_user.first_name}} {{dashboard_user.last_name}}
            </h4>
        {% endif %}
        <h5>
            @{{dashboard_user.username}}
        </h5>
        <div class="pt-2">
            <div id="following-div" class="d-inline-block pe-3 follow-div" data-url="{% url 'social:following' dashboard_user.id %}">
                <h6>following</h6>
                <p>{{dashboard_user.count_following}}</p>
            </div>
            <div id="followers-div" class="d-inline-block ps-3 follow-div" data-url="{% url 'social:followers' dashboard_user.id %}">
                <h6>followers</h6>
                <p id="follower-count">{{dashboard_user.count_followers}}</p>
            </div>
        </div>
      </div>
      <p class="card-text">{{dashboard_user.bio}}</p>
      {% if not dashboard_user == request.user and request.user.is_authenticated %}
      {% if not dashboard_user in request.user.following.all %}
        <button id="main-follow-button" class="btn btn-primary" data-id="{{dashboard_user.id}}">Follow</button>
      {% else %}
        <button id="main-follow-button" class="btn btn-danger"  data-id="{{dashboard_user.id}}">Unfollow</button>
      {% endif %}
      {% endif %}
    </div>
</div>
<div class="pt-4 pb-3">
  <div class="pb-4 activity-card d-inline-block">
    <div class="card text-center pt-2">
        <div class="card-body">
          <h3 class="card-title">Recent articles</h3>
          <div class="border-bottom pt-1"></div>
          <ul class="list-group list-group-flush">
            {% for article in recent_articles %}
            <li class="list-group-item text-start">
              <h4 class="mb-0">{{article.title}}</h4>
              <small>Updated on: {{article.updated_on}}</small>
              <p class="pt-2">{{article.content|striptags|truncatewords_html:20}}&nbsp;&nbsp;<a href="{% url 'knowledgebase:article' article.id %}">view more</a></p>
            </li>
            {% empty %}
            <li class="list-group-item text-start">
              <p class="pt-2 mb-0">No activity yet...</p>
            </li>
            {% endfor %}
          </ul>
        </div>
    </div>
  </div>
  <div class="kb-card activity-card d-inline-block float-end">
    <div class="card text-center pt-2">
      <div class="card-body">
        <h4 class="card-title">Check out {% if  dashboard_user.first_name and dashboard_user.last_name %} 
                                          {{dashboard_user.first_name}} {{dashboard_user.last_name}}'s 
                                        {% else %} {{dashboard_user.username}}'s 
                                        {% endif %} knowledgebase</h4>
        <div class="pt-4">
        <a href="{% url 'knowledgebase:kb' dashboard_user.username %}" class="btn btn-primary">View knowledgebase</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>


<!-- modals -->
<div id="following-followers-popup" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 id="modal-title" class="modal-title"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="modal-body" class="modal-body">
        <ul id="modal-list" class="list-group list-group-flush">
        </ul>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

{% block base_knowledegebase_scripts %}
{% static 'images/user.png' as default_user_img %}
{{default_user_img|json_script:"default_user_img"}}
{{request.user.id|json_script:"user_id"}}
<script src="{% static 'social/dashboard.js' %}"></script>
{% endblock base_knowledegebase_scripts %}

KnowledgeShare/templates/social/message_detail.html
{% extends 'layouts/base_knowledgebase.html' %}
{% load static %}

{% block title %}
Messages - {{chat_user.username}}
{% endblock title %}

{% block meta %}
<meta name="description" content="Message details between two users.">
{% endblock meta %}

{% block styles %}
<link rel="stylesheet" href='{% static 'social/message_detail.css' %}'>
{% endblock styles %}

{% block body %}
<div class="pb-5">
  <div class="col-lg-8">
    <div class="text-end pb-1">
      <button id="refresh-button" class="btn btn-success" style="background: rgb(0, 196, 65);">
        Refresh <i class="fa-solid fa-rotate"></i>
      </button>
    </div>
    <section class="msger shadow">
      <header class="msger-header">
        <div class="msger-header-title">@{{chat_user.username}}
        </div>
      </header>
    
      <main class="msger-chat">
        <div class="loader">
          <div class="text-center">
            <div class="spinner-grow text-info" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
          </div>
        </div>
        <div class="messages">
        </div>
      </main>
    
      <form class="msger-inputarea">
        <input type="text" class="msger-input" placeholder="Enter your message...">
        <button type="submit" class="msger-send-btn">Send</button>
      </form>
    </section>
  </div>
</div>

{% endblock body %}

{% block base_knowledegebase_scripts %}
{% url 'social:message_api' as messages_api_url%}
{{messages_api_url|json_script:"messages_api_url"}}
{% static 'images/user.png' as default_user_img %}
{{request.user.id|json_script:"request_user_id"}}
{{request.user.username|json_script:"request_username"}}
{% if request.user.profile_image %}
{{request.user.profile_image.url|json_script:"request_user_img"}}
{% else %}
{{default_user_img|json_script:"request_user_img"}}
{% endif %}
{{chat_user.id|json_script:"chat_user_id"}}
{{chat_user.username|json_script:"chat_username"}}
{% if chat_user.profile_image %}
{{chat_user.profile_image.url|json_script:"chat_user_img"}}
{% else %}
{{default_user_img|json_script:"chat_user_img"}}
{% endif %}
<script src="{% static 'social/message_detail.js' %}"></script>
{% endblock base_knowledegebase_scripts %}

KnowledgeShare/templates/social/messages.html
{% extends 'layouts/base_knowledgebase.html' %}
{% load static %}

{% block title %}
Messages
{% endblock title %}

{% block meta %}
<meta name="description" content="View messages.">
{% endblock meta %}

{% block styles %}
<link rel="stylesheet" href='{% static 'social/messages.css' %}'>
{% endblock styles %}

{% block body %}
<div class="pb-5">
  <div class="col-lg-7">
    <div class="d-inline-block">
      <h3>Messages</h3>
    </div>
    <div class="d-inline-block float-end">
      <a href="{% url 'social:new_message' %}" class="btn btn-primary">New Message</a>
    </div>
    <ul class="list-group list-group-flush pt-2 w-100">
      {% for message in object_list %}
      {% if request.user == message.sender %}
      <a href="{% url 'social:message_detail' message.recipient.username %}" class="text-decoration-none">
      {% else %}
      <a href="{% url 'social:message_detail' message.sender.username %}" class="text-decoration-none">
      {% endif %}
      <li class="list-group-item shadow-sm">
        <div>
        {% if request.user == message.sender %}
          <div class="d-inline-block float-start"><img src="{% if message.recipient.profile_image %}{{ message.recipient.profile_image.url}}{% else %}{% static 'images/user.png' %}{% endif %}" alt="Profile Picture" class="rounded-circle profile-img"></div>
          <div class="d-inline-block ps-2"><p class="mb-0" style="margin-top: 2.15rem !important;">@{{message.recipient.username}}</p></div>
        {% else %}
          <div class="d-inline-block float-start"><img src="{% if message.sender.profile_image %}{{ message.sender.profile_image.url}}{% else %}{% static 'images/user.png' %}{% endif %}" alt="Profile Picture" class="rounded-circle profile-img"></div>
          <div class="d-inline-block ps-2"><p class="mb-0" style="margin-top: 2.15rem !important;">@{{message.sender.username}}</p></div>
        {% endif %}
        <div class="d-inline-block float-end">
          <small>{{message.message_sent_date}}</small>
          <div class="d-block pt-4 float-end">
          {% if not message.message_read and not message.sender == request.user%}
            <span class="position-relative"><i class="fa-regular fa-envelope fa-xl"></i>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">!</span>
            </span>
          {% else %}
            <span><i class="fa-regular fa-envelope-open fa-xl"></i></span>
          {% endif %}
        </div>
        </div>
        </div>
        <div class="pt-2">
          <p>
            {{message.content|truncatewords:25}}
          </p>
        </div>
      </li>
      </a>
      {% empty %}
        No messages...
      {% endfor %}
      </ul>

      {% if is_paginated  %}
      <div class="pt-3">
          <span class="d-inline-block bottom-0">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
          </span>
          <span class="d-inline-block float-end">
              <nav>
                  <ul class="pagination">
                      {% if page_obj.has_previous %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                          </a>
                      </li>
                      {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                          </a>
                      </li>
                      {% endif %}
                      {% for page in page_obj.paginator.page_range %}
                      {% if page > page_obj.number|add:-3 and page < page_obj.number|add:3  %}
                      <li class="page-item {% if page_obj.number == page  %}active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                      {% endif %}
                      {% endfor %}
                      {% if page_obj.has_next %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                          </a>
                      </li>
                      {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                          </a>
                      </li>
                      {% endif %}
                  </ul>
                </nav>
          </span>
      </div>
      {% endif %}
  </div>
</div>

{% endblock body %}

KnowledgeShare/templates/social/new_message.html
{% extends 'layouts/base_knowledgebase.html' %}
{% load static %}

{% block title %}
New Message
{% endblock title %}

{% block meta %}
<meta name="description" content="Create a new message to send to another user.">
{% endblock meta %}

{% block styles %}
<link rel="stylesheet" href='{% static 'social/new_message.css' %}'>
{% endblock styles %}

{% block body %}
<div class="pb-5">
    <h3>Send Message</h3>
  <div class="col-md-6 bg-white p-4">
    <form method="post">
        {% csrf_token %}
        {{message_form}}
        <div class="pt-4 text-end">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </form>
  </div>
</div>

{% endblock body %}